### PR TITLE
Added brute force and optimized files for NGE

### LINKED ISSUE #672: Next Greater Element [Java]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS).

- [ ] Issue Title is in form `Algo/DS Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by kavyatripathi**
Fixes #672

#### By submitting this pull request I confirm I've read and complied with the below declarations.

- [x] I have read the [Contribution guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [coding guidelines](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#cs) for this project.
- [x] My code follows the [skeleton code structure](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md#sample).
- [x] This pull request has a descriptive title. For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once the Travis build passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

### CODE REVIEW

**Review by ishanksoni — APPROVED** [review]

**Comment by anshumanv** [comment]
Very strange, your PR should be against iiitv/algos, this is to neeraj's fork 😄

**Comment by kavyatripathi** [comment]
Sir i actually forked this repo when i was in first year during some
workshop. I tried to fork it again but it showed that it has already been
forked. What should i do? Is there any way to re-fork so that i can make a
PR in iiitv/algos ? 
I am just a beginner in git and github.

**Comment by anshumanv** [comment]
Yep delete this fork from repo settings, go to https://github.com/iiitv/algos and fork again.

**Comment by kavyatripathi** [comment]
Sir, I have created a new PR. Please check if it is fine.

**Comment by anshumanv** [comment]
Great! Will check in near future, meanwhile you can close this.

**Comment by kavyatripathi** [comment]
Okay, Thanku

**Pull request closed without merging**
